version: '3'

services:
  web:
    build: ./cacti
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - my-network

  db:
    build: ./database
    networks:
      - my-network

networks:
  my-network: